import { SpaceMono, DarkerGrotesque } from '@/fonts'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode,
}


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${SpaceMono.variable} ${DarkerGrotesque.variable}`}>
      <body>{children}</body>
    </html>
  )
}
