import { Analytics } from '@vercel/analytics/react';
import { InterFont } from '@/fonts'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode,
}


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${InterFont.variable}`}>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
