import { Analytics } from '@vercel/analytics/react';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode,
}


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body className='bg-background'>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
