name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm run build
      - name: run Lighthouse CI
        run: |
          pnpm install -g @lhci/cli@0.12.x
          lhci autorun